version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: TestDocker.Backend
    depends_on:
      - reverseproxy
    ports:
      - "5000"
    restart: always
  reverseproxy:
    build:
      context: .
      dockerfile: ./Nginx/Dockerfile
    container_name: TestDocker.ReverseProxy
    ports:
      - "80:80"
      - "443:443"
    restart: always
  